# Makefile.rules for parallelGBC 0.2 and later
#  
# With this file you can configure the compilation of the tool.
#
# This file is part of parallelGBC, a parallel groebner basis computation tool.
#
# parallelGBC is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# parallelGBC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with parallelGBC.  If not, see <http://www.gnu.org/licenses/>.

# Set your Compiler. Attention you need a compiler which supports the  C++11 standard
CXX = /usr/bin/g++

# Configure CXXFLAGS. If you want to use parallelism do not remove "-fopenmp"
# COEFF_BITS defines the length of the coefficents. If you need fields larger than 32003,
# you have to use 32 oder 64.
# PGBC_USE_SSE1 enables sse optimizations in the field arithmetics (currently requires GCC)
# 
# the following CXXFLAGS are for the GNU COMPILER:
#CXXFLAGS = -fPIC -Wall -fopenmp -O2 -pipe -D'PGBC_COEFF_BITS=16' -std=c++0x
# Possible FLAGS:
CXXFLAGS = -fPIC -Wall -fopenmp -O3 -march=native -pipe -D'PGBC_COEFF_BITS=16' -D'PGBC_USE_SSE=1' -std=c++0x
# DEBUG FLAGS:
#CXXFLAGS = -fPIC -Wall -pg -g3 -gdwarf-2 -D'PGBC_USE_SSE=1' -D'PGBC_USE_SSE=1' -std=c++0x

# Where the compiled (static) library will be stored.
LIBRARY = ../lib/libf4.a

# Below you find some generic make rules ...

dummy:
	echo "Please use the Makefile in the main directory or specify a target"

%.o: %.C ../include/%.H ../Makefile.rules
	$(CXX) $(CXXFLAGS) -c $<

%.bin: %.C $(LIBRARY)
	$(CXX) $(CXXFLAGS) -o $(<:%.C=%.bin) $< $(LIBRARY) -lboost_regex

objclean:
	rm -f $(OBJ)
