#
# Makefile.rules for parallelGBC 0.5 and later
#  
# With this file you can configure the compilation of the tool.
#
######################
#
# This file is part of parallelGBC, a parallel groebner basis computation tool.
#
# parallelGBC is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# parallelGBC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with parallelGBC.  If not, see <http://www.gnu.org/licenses/>.

# Set your Compiler. Attention you need a compiler which supports the  C++11 standard
CXX = /usr/bin/g++

# Configure CXXFLAGS. 
# COEFF_BITS defines the length of the coefficents. If you need large coefficient fields
# you should choose 32. If you want to get the most performance, you can choose 8. But
# for most cases the default value of 16 should do it.
# PGBC_USE_SSE1 enables sse optimizations in the field arithmetics (currently requires GCC)
# PGBC_SORTING defines the sorting for the reduction, the behaviour only changes if this
# value is set to one. Further sortings may follow
# 
# the following CXXFLAGS are for the GNU COMPILER:
CXXFLAGS = -fPIC -Wall -fopenmp -O2 -pipe -D'PGBC_COEFF_BITS=16' -D'PGBC_SORTING=1' -std=c++0x
# Possible FLAGS:
#CXXFLAGS = -fPIC -Wall -fopenmp -O3 -march=native -pipe -D'PGBC_COEFF_BITS=16' -D'PGBC_USE_SSE=1' -D'PGDBC_SORTING=1' -std=c++0x
# DEBUG FLAGS:
#CXXFLAGS = -fPIC -Wall -fopenmp -O2 -pipe -D'PGBC_COEFF_BITS=16' -D'PGBC_USE_SSE=1' -std=c++0x -g3 -pg -gdwarf-2

# Where the compiled (static) library will be stored.
LIBRARY = ../lib/libf4.a

# Below you find some generic make rules ...

dummy:
	echo "Please use the Makefile in the main directory or specify a target"

%.o: %.C ../include/%.H ../Makefile.rules
	$(CXX) $(CXXFLAGS) -c $<

%.bin: %.C $(LIBRARY)
	$(CXX) $(CXXFLAGS) -o $(<:%.C=%.bin) $< $(LIBRARY) -lboost_regex -ltbb

objclean:
	rm -f $(OBJ)
